#!/bin/sh

DESKTOP=$(xdg-user-dir DESKTOP)

set -e

echo "Updating launchers"

if [ -L $HOME/.local/share/applications/openjk_amd64_sp.desktop ];
then
   echo "Updating openjk_amd64_sp.desktop"
   rm $HOME/.local/share/applications/openjk_amd64_sp.desktop
   cp /opt/free-engineer/jediacademy/openjk_amd64_sp.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/openjk_amd64_sp.desktop
fi

if [ -L $HOME/.local/share/applications/openjk_i386_sp.desktop ];
then
   echo "Updating openjk_i386_sp.desktop"
   rm $HOME/.local/share/applications/openjk_i386_sp.desktop
   cp /opt/free-engineer/jediacademy/openjk_i386_sp.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/openjk_i386_sp.desktop
fi

if [ -L $HOME/.local/share/applications/openjk_amd64_mp.desktop ];
then
   echo "Updating openjk_amd64_mp.desktop"
   rm $HOME/.local/share/applications/openjk_amd64_mp.desktop
   cp /opt/free-engineer/jediacademy/openjk_amd64_mp.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/openjk_amd64_mp.desktop
fi

if [ -L $HOME/.local/share/applications/openjk_i386_mp.desktop ];
then
   echo "Updating openjk_i386_mp.desktop"
   rm $HOME/.local/share/applications/openjk_i386_mp.desktop
   cp /opt/free-engineer/jediacademy/openjk_i386_mp.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/openjk_i386_mp.desktop
fi

if [ -L $DESKTOP/openjk_amd64_sp.desktop ];
then
   echo "Updating openjk_amd64_sp.desktop"
   rm $DESKTOP/openjk_amd64_sp.desktop
   cp /opt/free-engineer/jediacademy/openjk_amd64_sp.desktop $DESKTOP/
   chmod 777 $DESKTOP/openjk_amd64_sp.desktop
fi

if [ -L $DESKTOP/openjk_i386_sp.desktop ];
then
   echo "Updating openjk_i386_sp.desktop"
   rm $DESKTOP/openjk_i386_sp.desktop
   cp /opt/free-engineer/jediacademy/openjk_i386_sp.desktop $DESKTOP/
   chmod 777 $DESKTOP/openjk_i386_sp.desktop
fi

if [ -L $DESKTOP/openjk_amd64_mp.desktop ];
then
   echo "Updating openjk_amd64_mp.desktop"
   rm $DESKTOP/openjk_amd64_mp.desktop
   cp /opt/free-engineer/jediacademy/openjk_amd64_mp.desktop $DESKTOP/
   chmod 777 $DESKTOP/openjk_amd64_mp.desktop
fi

if [ -L $DESKTOP/openjk_i386_mp.desktop ];
then
   echo "Updating openjk_i386_mp.desktop"
   rm $DESKTOP/openjk_i386_mp.desktop
   cp /opt/free-engineer/jediacademy/openjk_i386_mp.desktop $DESKTOP/
   chmod 777 $DESKTOP/openjk_i386_mp.desktop
fi

if [ -L $HOME/.local/share/applications/avp.desktop ];
then
   echo "Updating avp.desktop"
   rm $HOME/.local/share/applications/avp.desktop
   cp /opt/free-engineer/avp/avp.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/avp.desktop
fi

if [ -L $DESKTOP/avp.desktop ];
then
   echo "Updating avp.desktop"
   rm $DESKTOP/avp.desktop
   cp /opt/free-engineer/avp/avp.desktop $DESKTOP/
   chmod 777 $DESKTOP/avp.desktop
fi

if [ -L $HOME/.local/share/applications/doom3.desktop ];
then
   echo "Updating doom3.desktop"
   rm $HOME/.local/share/applications/doom3.desktop
   cp /opt/free-engineer/doom3/doom3.desktop $HOME/.local/share/applications/
   chmod 777 $HOME/.local/share/applications/doom3.desktop
fi

if [ -L $DESKTOP/doom3.desktop ];
then
   echo "Updating doom3.desktop"
   rm $DESKTOP/doom3.desktop
   cp /opt/free-engineer/doom3/doom3.desktop $DESKTOP/
   chmod 777 $DESKTOP/doom3.desktop
fi

exit 0
